// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project bd6f01237f00e787 "Hover Mask Reveal - Community (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Primary' | 'Secondary' // Variant
 * title?: string // Title
 * onp4yJ9jM9KCHange?: undefined // onp4yJ9jM9KCHange
 * link?: string // Link
}} Props

 */
import { routes } from "./chunks/chunk-L62PYL7U.js";

// virtual:button
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/imYcgvXCMaLH8sOQe2Jn/bDLOEC0dLq6c7IJidZgj/Apo5ZZ6Tz.js
import { jsx as _jsx4, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls4,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType7,
	cx as cx2,
	forwardLoader,
	getFonts as getFonts2,
	Link,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion3,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef4 } from "react";

// /:https://framerusercontent.com/modules/ciE4EHUQgGBIX79KdSTV/DagWMgx7X2M8c6HUgq5c/TNRZ_28SA.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType6,
	cx,
	getFonts,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React3 from "react";

// /:https://framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/RfHh9MIwqlgi04HKZ3Qo/Clipboard.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useCallback as useCallback2 } from "react";
import { addPropertyControls, ControlType as ControlType4 } from "unframer";
import { motion } from "unframer";

// /:https://framerusercontent.com/modules/VTUDdizacRHpwbkOamr7/AykinQJbgwl92LvMGZwu/constants.js
import { ControlType } from "unframer";
var fontStack = `"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`;
var containerStyles = {
	position: "relative",
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
var emptyStateStyle = {
	...containerStyles,
	borderRadius: 6,
	background: "rgba(136, 85, 255, 0.3)",
	color: "#85F",
	border: "1px dashed #85F",
	flexDirection: "column",
};
var defaultEvents = {
	onClick: {
		type: ControlType.EventHandler,
	},
	onMouseEnter: {
		type: ControlType.EventHandler,
	},
	onMouseLeave: {
		type: ControlType.EventHandler,
	},
};
var fontSizeOptions = {
	type: ControlType.Number,
	title: "Font Size",
	min: 2,
	max: 200,
	step: 1,
	displayStepper: true,
};
var fontControls = {
	font: {
		type: ControlType.Boolean,
		title: "Font",
		defaultValue: false,
		disabledTitle: "Default",
		enabledTitle: "Custom",
	},
	fontFamily: {
		type: ControlType.String,
		title: "Family",
		placeholder: "Inter",
		hidden: ({ font }) => !font,
	},
	fontWeight: {
		type: ControlType.Enum,
		title: "Weight",
		options: [100, 200, 300, 400, 500, 600, 700, 800, 900],
		optionTitles: [
			"Thin",
			"Extra-light",
			"Light",
			"Regular",
			"Medium",
			"Semi-bold",
			"Bold",
			"Extra-bold",
			"Black",
		],
		hidden: ({ font }) => !font,
	},
};

// /:https://framerusercontent.com/modules/D4TWeLfcxT6Tysr2BlYg/iZjmqdxVx1EOiM3k1FaW/useOnNavigationTargetChange.js
import { useIsInCurrentNavigationTarget } from "unframer";
import { useEffect } from "react";

// /:https://framerusercontent.com/modules/ExNgrA7EJTKUPpH6vIlN/eiOrSJ2Ab5M9jPCvVwUz/useConstant.js
import { useRef } from "react";

// /:https://framerusercontent.com/modules/D2Lz5CmnNVPZFFiZXalt/QaCzPbriZBfXWZIIycFI/colorFromToken.js
import { Color } from "unframer";

// /:https://framerusercontent.com/modules/3mKFSGQqKHV82uOV1eBc/5fbRLvOpxZC0JOXugvwm/isMotionValue.js
import { MotionValue } from "unframer";

// /:https://framerusercontent.com/modules/xDiQsqBGXzmMsv7AlEVy/uhunpMiNsbXxzjlXsg1y/useUniqueClassName.js
import * as React from "react";

// /:https://framerusercontent.com/modules/ETACN5BJyFTSo0VVDJfu/NHRqowOiXkF9UwOzczF7/variantUtils.js
import { ControlType as ControlType2 } from "unframer";

// /:https://framerusercontent.com/modules/eMBrwoqQK7h6mEeGQUH8/GuplvPJVjmxpk9zqOTcb/isBrowser.js
import { useMemo } from "react";

// /:https://framerusercontent.com/modules/v9AWX2URmiYsHf7GbctE/XxKAZ9KlhWqf5x1JMyyF/useOnChange.js
import { useEffect as useEffect3 } from "react";

// /:https://framerusercontent.com/modules/kNDwabfjDEb3vUxkQlZS/fSIr3AOAYbGlfSPgXpYu/useAutoMotionValue.js
import { useCallback, useEffect as useEffect4, useRef as useRef2 } from "react";
import { motionValue, animate, RenderTarget } from "unframer";

// /:https://framerusercontent.com/modules/cuQH4dmpDnV8YK1mSgQX/KqRXqunFjE6ufhpc7ZRu/useFontControls.js
import { fontStore } from "unframer";
import { useEffect as useEffect5 } from "react";
var fontWeights = {
	100: "Thin",
	200: "Extra-light",
	300: "Light",
	400: "Regular",
	500: "Medium",
	600: "Semi-bold",
	700: "Bold",
	800: "Extra-bold",
	900: "Black",
};
function useFontControls(props) {
	const {
		fontFamily = "Inter",
		fontSize = 16,
		fontWeight = 400,
		font = false,
	} = props;
	const fontWeightName = fontWeights[fontWeight];
	const customFontStack = `"${fontFamily} ${fontWeightName}", "${fontFamily}", ${fontStack}`;
	const fontFamilyStyle = fontFamily
		? {
				fontSize,
				fontWeight,
				fontFamily: customFontStack,
			}
		: {
				fontSize,
				fontWeight,
			};
	const fetchCustomFonts = async () => {
		await fontStore
			.loadWebFontsFromSelectors([
				`CUSTOM;${fontFamily}`,
				`CUSTOM;${fontFamily} ${fontWeightName}`,
				`GF;${fontFamily}-${fontWeightName.toLowerCase()}`,
			])
			.catch((e) => console.error(e));
	};
	useEffect5(() => {
		if (font) fetchCustomFonts();
	}, [font, fontFamily, fontWeight]);
	return fontFamilyStyle;
}

// /:https://framerusercontent.com/modules/afBE9Yx1W6bY5q32qPxe/m3q7puE2tbo1S2C0s0CT/useRenderTarget.js
import { useMemo as useMemo2 } from "react";
import { RenderTarget as RenderTarget2 } from "unframer";

// /:https://framerusercontent.com/modules/zGkoP8tPDCkoBzMdt5uq/0zFSjxIYliHxrQQnryFX/useControlledState.js
import * as React2 from "react";

// /:https://framerusercontent.com/modules/5SM58HxZHxjjv7aLMOgQ/WXz9i6mVki0bBCrKdqB3/propUtils.js
import { useMemo as useMemo3 } from "react";
import { ControlType as ControlType3 } from "unframer";
function useRadius(props) {
	const {
		borderRadius,
		isMixedBorderRadius,
		topLeftRadius,
		topRightRadius,
		bottomRightRadius,
		bottomLeftRadius,
	} = props;
	const radiusValue = useMemo3(
		() =>
			isMixedBorderRadius
				? `${topLeftRadius}px ${topRightRadius}px ${bottomRightRadius}px ${bottomLeftRadius}px`
				: `${borderRadius}px`,
		[
			borderRadius,
			isMixedBorderRadius,
			topLeftRadius,
			topRightRadius,
			bottomRightRadius,
			bottomLeftRadius,
		],
	);
	return radiusValue;
}
var borderRadiusControl = {
	borderRadius: {
		title: "Radius",
		type: ControlType3.FusedNumber,
		toggleKey: "isMixedBorderRadius",
		toggleTitles: ["Radius", "Radius per corner"],
		valueKeys: [
			"topLeftRadius",
			"topRightRadius",
			"bottomRightRadius",
			"bottomLeftRadius",
		],
		valueLabels: ["TL", "TR", "BR", "BL"],
		min: 0,
	},
};
function usePadding(props) {
	const {
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
	} = props;
	const paddingValue = useMemo3(
		() =>
			paddingPerSide
				? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
				: padding,
		[
			padding,
			paddingPerSide,
			paddingTop,
			paddingRight,
			paddingBottom,
			paddingLeft,
		],
	);
	return paddingValue;
}
var paddingControl = {
	padding: {
		type: ControlType3.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
		title: "Padding",
	},
};

// /:https://framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/RfHh9MIwqlgi04HKZ3Qo/Clipboard.js
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var __unframerNavigator =
	typeof __unframerWindow !== "undefined" ? navigator : void 0;
function Clipboard(props) {
	const {
		label,
		content,
		fill,
		color,
		style,
		onClick,
		font,
		hoverOptions,
		...rest
	} = props;
	const deprecatedFont = useFontControls({
		fontWeight: 500,
		...rest,
	});
	const borderRadius = useRadius(props);
	const paddingValue = usePadding(props);
	const handleClick = useCallback2(() => {
		var ref;
		(ref = __unframerNavigator.clipboard) === null || ref === void 0
			? void 0
			: ref.writeText(content);
		onClick === null || onClick === void 0 ? void 0 : onClick();
	}, [onClick, content]);
	return (
		<motion.button
			style={{
				border: "none",
				outline: "none",
				resize: "none",
				width: "max-content",
				wordBreak: "break-word",
				overflowWrap: "break-word",
				WebkitTapHighlightColor: "rgba(0, 0, 0, 0)",
				letterSpacing: "-0.2px",
				display: "flex",
				justifyContent: "center",
				alignItems: "center",
				background: fill,
				borderRadius,
				cursor: "pointer",
				padding: paddingValue,
				color,
				...deprecatedFont,
				...font,
				...style,
			}}
			onClick={handleClick}
			{...rest}
			whileHover={hoverOptions}
			transition={
				hoverOptions === null || hoverOptions === void 0
					? void 0
					: hoverOptions.transition
			}
		>
			{label}
		</motion.button>
	);
}
addPropertyControls(Clipboard, {
	content: {
		type: ControlType4.String,
		title: "Content",
		displayTextArea: true,
		description: "When clicked, this content will be copied to the clipboard.",
	},
	label: {
		type: ControlType4.String,
		title: "Label",
		defaultValue: "Copy to Clipboard",
	},
	fill: {
		type: ControlType4.Color,
		title: "Fill",
		defaultValue: "#06F",
	},
	color: {
		type: ControlType4.Color,
		title: "Text",
		defaultValue: "#fff",
	},
	font: {
		// @ts-ignore - Internal
		type: ControlType4.Font,
		controls: "extended",
		defaultValue: {
			fontSize: 16,
		},
	},
	hoverOptions: {
		type: ControlType4.Object,
		title: "Hover",
		buttonTitle: "Effect",
		optional: true,
		controls: {
			scale: {
				type: ControlType4.Number,
				title: "Scale",
				min: 0,
				max: 10,
				displayStepper: true,
				step: 0.01,
				defaultValue: 1.1,
			},
			backgroundColor: {
				type: ControlType4.Color,
				title: "Fill",
				defaultValue: "#0088FF",
				optional: true,
			},
			color: {
				type: ControlType4.Color,
				title: "Color",
				defaultValue: "#FFF",
				optional: true,
			},
			transition: {
				type: ControlType4.Transition,
				title: "Transition",
				defaultValue: {
					type: "spring",
					stiffness: 400,
					damping: 30,
				},
			},
		},
	},
	padding: {
		type: ControlType4.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
		title: "Padding",
		defaultValue: 10,
	},
	borderRadius: {
		title: "Radius",
		type: ControlType4.FusedNumber,
		toggleKey: "isMixedBorderRadius",
		toggleTitles: ["Radius", "Radius per corner"],
		valueKeys: [
			"topLeftRadius",
			"topRightRadius",
			"bottomRightRadius",
			"bottomLeftRadius",
		],
		valueLabels: ["TL", "TR", "BR", "BL"],
		min: 0,
		defaultValue: 50,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/I1DC9cTt2FcHsDUAaRxW/pUC2Q4HS9uuwHefZZ6Oq/SVG.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import { useState as useState3, useEffect as useEffect7 } from "react";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType5,
} from "unframer";
function SVG(props) {
	const [customSvgElement, setCustomSvgElement] = useState3(null);
	useEffect7(() => {
		const svgContent = props.customSvgCode;
		processCustomSVGContent(svgContent);
	});
	const processCustomSVGContent = (svgContent) => {
		const replacements = [
			[/width="[^"]*"/, 'width="100%"'],
			[/height="[^"]*"/, 'height="100%"'],
		];
		const hasCustomStroke = svgContent.includes('stroke="');
		const hasCustomStrokeWidth = svgContent.includes('stroke-width="');
		const hasLineCap = svgContent.includes('stroke-linecap="');
		const hasLineJoin = svgContent.includes('stroke-linejoin="');
		if (svgContent.includes("<circle")) {
			const circleFillRegex = /<circle[^>]*fill="([^"]*)"/;
			const match = svgContent.match(circleFillRegex);
			if (match) {
				const updatedCircle = match[0].replace(match[1], props.customColor);
				svgContent = svgContent.replace(circleFillRegex, updatedCircle);
			} else {
				replacements.push([/<circle/g, `<circle fill="${props.customColor}"`]);
			}
		}
		if (hasCustomStroke) {
			if (!hasLineCap) {
				replacements.push([/<path/g, `<path stroke="${props.customColor}"`]);
			} else {
				replacements.push([
					/<path/g,
					`<path stroke="${props.customColor}" stroke-linecap="${props.lineCap}"`,
				]);
			}
			if (hasCustomStrokeWidth) {
				replacements.push([
					/stroke-width="(?!0\b)\d+(\.\d+)?"/g,
					`stroke-width="${props.customStrokeWidth}"`,
				]);
			}
		} else {
			replacements.push([/<path/g, `<path fill="${props.customColor}"`]);
		}
		if (svgContent.includes('overflow="')) {
			replacements.push([/overflow="[^"]*"/, `overflow="visible"`]);
		} else {
			replacements.push([/<svg/, `<svg overflow="visible"`]);
		}
		if (!hasLineJoin) {
			replacements.push([
				/<path/g,
				`<path stroke-linejoin="${props.lineJoin}"`,
			]);
		} else {
			replacements.push([
				/stroke-linejoin="[^"]*"/,
				`stroke-linejoin="${props.lineJoin}"`,
			]);
		}
		replacements.forEach(([regex, replacement]) => {
			svgContent = svgContent.replace(regex, replacement);
		});
		setCustomSvgElement(svgContent);
	};
	const customContainerStyle = {
		padding: `${props.customPadding}px`,
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		overflow: "visible",
	};
	return (
		<div
			dangerouslySetInnerHTML={{
				__html: customSvgElement,
			}}
			style={customContainerStyle}
		/>
	);
}
SVG.defaultProps = {
	customSvgCode: `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M11.9996 4.58607L19.414 12.0001L22.9139 8.50015L15.4997 1.08594L11.9996 4.58607Z" fill="black"/> <path d="M18.403 13.8175L10.1822 5.59708L5.63438 7.25082L3.08203 19.5021L8.15387 14.4302C8.0427 14.1472 7.98166 13.839 7.98166 13.5166C7.98166 12.1359 9.10095 11.0166 10.4817 11.0166C11.8624 11.0166 12.9817 12.1359 12.9817 13.5166C12.9817 14.8973 11.8624 16.0166 10.4817 16.0166C10.1592 16.0166 9.85109 15.9556 9.56811 15.8444L4.49378 20.9188L16.7491 18.3656L18.403 13.8175Z" fill="black"/> </svg>`,
	customColor: "#ffffff",
	customPadding: 0,
	customStrokeWidth: 2,
	lineCap: "butt",
	lineJoin: "miter",
};
addPropertyControls2(SVG, {
	customSvgCode: {
		type: ControlType5.String,
		title: "SVG Code",
		displayTextArea: false,
	},
	customColor: {
		type: ControlType5.Color,
		title: "Color",
		defaultValue: "#ffffff",
	},
	customStrokeWidth: {
		type: ControlType5.Number,
		title: "Stroke",
		defaultValue: 2,
		min: 0,
		step: 0.1,
		displayStepper: true,
		hidden: (props) => !props.customSvgCode.includes('stroke="'),
	},
	customPadding: {
		type: ControlType5.Number,
		title: "Padding",
		defaultValue: 0,
		min: 0,
		step: 1,
		displayStepper: true,
	},
	lineCap: {
		type: ControlType5.Enum,
		title: "Line Cap",
		options: ["butt", "round", "square"],
		optionTitles: ["Butt", "Round", "Square"],
		defaultValue: "butt",
		hidden: (props) => !props.customSvgCode.includes('stroke="'),
	},
	lineJoin: {
		type: ControlType5.Enum,
		title: "Line Join",
		options: ["round", "miter", "bevel"],
		optionTitles: ["Round", "Miter", "Bevel"],
		defaultValue: "miter",
		hidden: (props) => !props.customSvgCode.includes('stroke="'),
	},
});
var stdin_default = SVG;

// /:https://framerusercontent.com/modules/ciE4EHUQgGBIX79KdSTV/DagWMgx7X2M8c6HUgq5c/TNRZ_28SA.js
var SVGFonts = getFonts(stdin_default);
var ClipboardFonts = getFonts(Clipboard);
var enabledGestures = {
	ZPBoeSRM1: {
		hover: true,
	},
};
var cycleOrder = ["ZPBoeSRM1", "uKcSpW62M"];
var serializationHash = "framer-xqJWl";
var variantClassNames = {
	uKcSpW62M: "framer-v-1wahjrx",
	ZPBoeSRM1: "framer-v-1e6klh1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 45,
	delay: 0,
	mass: 1,
	stiffness: 600,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2(React3.Fragment);
var humanReadableVariantMap = {
	Copied: "uKcSpW62M",
	Default: "ZPBoeSRM1",
};
var getProps = ({
	bG,
	bGHover,
	clipboardContent,
	height,
	iconCopied,
	iconCopy,
	icons,
	id,
	labelCopied,
	labelCopy,
	labels,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_ref4,
		_ref5,
		_ref6,
		_humanReadableVariantMap_props_variant,
		_ref7,
		_ref8,
		_ref9;
	return {
		...props,
		aCeOAHQBL:
			(_ref =
				labels !== null && labels !== void 0 ? labels : props.aCeOAHQBL) !==
				null && _ref !== void 0
				? _ref
				: "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		b8ei7OpHv:
			(_ref1 = bG !== null && bG !== void 0 ? bG : props.b8ei7OpHv) !== null &&
			_ref1 !== void 0
				? _ref1
				: "var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
		bcOKL_7fc:
			(_ref2 =
				iconCopy !== null && iconCopy !== void 0
					? iconCopy
					: props.bcOKL_7fc) !== null && _ref2 !== void 0
				? _ref2
				: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M21 3H7V7H3V21H17V17H21V3ZM17 15H19V5H9V7H17V15Z" fill="white"/> </svg>',
		bPCJyrIbK:
			(_ref3 =
				iconCopied !== null && iconCopied !== void 0
					? iconCopied
					: props.bPCJyrIbK) !== null && _ref3 !== void 0
				? _ref3
				: '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3 15L9.29412 20L21 4" stroke="black" stroke-width="2" stroke-linecap="square"/> </svg>',
		PbW7K4Unr:
			(_ref4 = icons !== null && icons !== void 0 ? icons : props.PbW7K4Unr) !==
				null && _ref4 !== void 0
				? _ref4
				: "var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		qIDNNRI0q:
			(_ref5 =
				clipboardContent !== null && clipboardContent !== void 0
					? clipboardContent
					: props.qIDNNRI0q) !== null && _ref5 !== void 0
				? _ref5
				: "Copied text.",
		rIGEnoYqD:
			(_ref6 =
				labelCopied !== null && labelCopied !== void 0
					? labelCopied
					: props.rIGEnoYqD) !== null && _ref6 !== void 0
				? _ref6
				: "Copied",
		variant:
			(_ref7 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref7 !== void 0
				? _ref7
				: "ZPBoeSRM1",
		wr2g_fjxZ:
			(_ref8 =
				bGHover !== null && bGHover !== void 0 ? bGHover : props.wr2g_fjxZ) !==
				null && _ref8 !== void 0
				? _ref8
				: "rgb(212, 212, 212)",
		zhU3xY_Ux:
			(_ref9 =
				labelCopy !== null && labelCopy !== void 0
					? labelCopy
					: props.zhU3xY_Ux) !== null && _ref9 !== void 0
				? _ref9
				: "Copy component",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		bcOKL_7fc,
		zhU3xY_Ux,
		bPCJyrIbK,
		rIGEnoYqD,
		b8ei7OpHv,
		wr2g_fjxZ,
		PbW7K4Unr,
		aCeOAHQBL,
		qIDNNRI0q,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ZPBoeSRM1",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap12ili4c = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("uKcSpW62M");
	});
	const onAppear1x21iu3 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("ZPBoeSRM1"), 1500);
	});
	useOnVariantChange(baseVariant, {
		uKcSpW62M: onAppear1x21iu3,
	});
	const ref1 = React3.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "uKcSpW62M") return false;
		return true;
	};
	const defaultLayoutId = React3.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1e6klh1",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ZPBoeSRM1"}
						onTap={onTap12ili4c}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor: b8ei7OpHv,
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							...style,
						}}
						variants={{
							"ZPBoeSRM1-hover": {
								backgroundColor: wr2g_fjxZ,
							},
						}}
						{...addPropertyOverrides(
							{
								"ZPBoeSRM1-hover": {
									"data-framer-name": void 0,
								},
								uKcSpW62M: {
									"data-framer-name": "Copied",
									onTap: void 0,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-b17vs8"}
							data-framer-name={"Content - Default"}
							layoutDependency={layoutDependency}
							layoutId={"HO8imGSxm"}
							style={{
								filter: "none",
								opacity: 1,
								scale: 1,
								WebkitFilter: "none",
							}}
							variants={{
								uKcSpW62M: {
									filter: "blur(4px)",
									opacity: 0,
									scale: 1.2,
									WebkitFilter: "blur(4px)",
								},
							}}
						>
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-1vvcich-container"}
									layoutDependency={layoutDependency}
									layoutId={"kcF2glrbr-container"}
								>
									{_jsx3(stdin_default, {
										customColor: PbW7K4Unr,
										customPadding: 0,
										customStrokeWidth: 2,
										customSvgCode: bcOKL_7fc,
										height: "100%",
										id: "kcF2glrbr",
										layoutId: "kcF2glrbr",
										lineCap: "butt",
										lineJoin: "miter",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</motion2.div>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-my6yxr"}
								fonts={["Inter-Medium"]}
								layoutDependency={layoutDependency}
								layoutId={"PLHmDyJZe"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-aCeOAHQBL-TNRZ_28SA)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--variable-reference-aCeOAHQBL-TNRZ_28SA": aCeOAHQBL,
								}}
								text={zhU3xY_Ux}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React3.Fragment>
									<motion2.p
										style={{
											"--font-selector": "SW50ZXItTWVkaXVt",
											"--framer-font-family":
												'"Inter", "Inter Placeholder", sans-serif',
											"--framer-font-weight": "500",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-aCeOAHQBL-TNRZ_28SA))",
										}}
									>
										{"Copy component"}
									</motion2.p>
								</React3.Fragment>
							</RichText>
						</motion2.div>
						<motion2.div
							className={"framer-13w9vkp"}
							data-framer-name={"Content - Copied"}
							layoutDependency={layoutDependency}
							layoutId={"S3ux1NmzH"}
							style={{
								filter: "blur(4px)",
								opacity: 0,
								scale: 0.6,
								WebkitFilter: "blur(4px)",
							}}
							transformTemplate={transformTemplate1}
							variants={{
								uKcSpW62M: {
									filter: "blur(0px)",
									opacity: 1,
									scale: 1,
									WebkitFilter: "blur(0px)",
								},
							}}
						>
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-1xgx2kr-container"}
									layoutDependency={layoutDependency}
									layoutId={"NhgN7bFV5-container"}
								>
									{_jsx3(stdin_default, {
										customColor: PbW7K4Unr,
										customPadding: 0,
										customStrokeWidth: 2,
										customSvgCode: bPCJyrIbK,
										height: "100%",
										id: "NhgN7bFV5",
										layoutId: "NhgN7bFV5",
										lineCap: "butt",
										lineJoin: "miter",
										style: {
											height: "100%",
											width: "100%",
										},
										width: "100%",
									})}
								</motion2.div>
							</ComponentViewportProvider>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1pcwz85"}
								fonts={["Inter-Medium"]}
								layoutDependency={layoutDependency}
								layoutId={"qiIaYll5G"}
								style={{
									"--extracted-r6o4lv":
										"var(--variable-reference-aCeOAHQBL-TNRZ_28SA)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									"--variable-reference-aCeOAHQBL-TNRZ_28SA": aCeOAHQBL,
								}}
								text={rIGEnoYqD}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React3.Fragment>
									<motion2.p
										style={{
											"--font-selector": "SW50ZXItTWVkaXVt",
											"--framer-font-family":
												'"Inter", "Inter Placeholder", sans-serif',
											"--framer-font-weight": "500",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--variable-reference-aCeOAHQBL-TNRZ_28SA))",
										}}
									>
										{"Copied"}
									</motion2.p>
								</React3.Fragment>
							</RichText>
						</motion2.div>
						{isDisplayed() && (
							<ComponentViewportProvider>
								<motion2.div
									className={"framer-1e0ld87-container"}
									layoutDependency={layoutDependency}
									layoutId={"JZi1Vftiv-container"}
								>
									<Clipboard
										borderRadius={100}
										bottomLeftRadius={100}
										bottomRightRadius={100}
										color={"rgba(255, 255, 255, 0)"}
										content={qIDNNRI0q}
										fill={"rgba(0, 102, 255, 0)"}
										font={{}}
										height={"100%"}
										id={"JZi1Vftiv"}
										isMixedBorderRadius={false}
										label={""}
										layoutId={"JZi1Vftiv"}
										padding={0}
										paddingBottom={0}
										paddingLeft={0}
										paddingPerSide={false}
										paddingRight={0}
										paddingTop={0}
										style={{
											height: "100%",
											width: "100%",
										}}
										topLeftRadius={100}
										topRightRadius={100}
										width={"100%"}
									/>
								</motion2.div>
							</ComponentViewportProvider>
						)}
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-xqJWl.framer-o9r9un, .framer-xqJWl .framer-o9r9un { display: block; }",
	".framer-xqJWl.framer-1e6klh1 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 44px; justify-content: center; overflow: hidden; padding: 0px 20px 0px 20px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-xqJWl .framer-b17vs8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-xqJWl .framer-1vvcich-container, .framer-xqJWl .framer-1xgx2kr-container { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-xqJWl .framer-my6yxr, .framer-xqJWl .framer-1pcwz85 { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-xqJWl .framer-13w9vkp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; left: 49%; overflow: hidden; padding: 0px; position: absolute; top: 50%; width: min-content; z-index: 1; }",
	".framer-xqJWl .framer-1e0ld87-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 4; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-xqJWl.framer-1e6klh1, .framer-xqJWl .framer-b17vs8, .framer-xqJWl .framer-13w9vkp { gap: 0px; } .framer-xqJWl.framer-1e6klh1 > *, .framer-xqJWl .framer-b17vs8 > *, .framer-xqJWl .framer-13w9vkp > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-xqJWl.framer-1e6klh1 > :first-child, .framer-xqJWl .framer-b17vs8 > :first-child, .framer-xqJWl .framer-13w9vkp > :first-child { margin-left: 0px; } .framer-xqJWl.framer-1e6klh1 > :last-child, .framer-xqJWl .framer-b17vs8 > :last-child, .framer-xqJWl .framer-13w9vkp > :last-child { margin-right: 0px; } }",
];
var FramerTNRZ_28SA = withCSS(Component, css, "framer-xqJWl");
var stdin_default2 = FramerTNRZ_28SA;
FramerTNRZ_28SA.displayName = "Copy Button";
FramerTNRZ_28SA.defaultProps = {
	height: 44,
	width: 203,
};
addPropertyControls3(FramerTNRZ_28SA, {
	variant: {
		options: ["ZPBoeSRM1", "uKcSpW62M"],
		optionTitles: ["Default", "Copied"],
		title: "Variant",
		type: ControlType6.Enum,
	},
	bcOKL_7fc: {
		defaultValue:
			'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M21 3H7V7H3V21H17V17H21V3ZM17 15H19V5H9V7H17V15Z" fill="white"/> </svg>',
		displayTextArea: false,
		title: "Icon - Copy",
		type: ControlType6.String,
	},
	zhU3xY_Ux: {
		defaultValue: "Copy component",
		displayTextArea: false,
		title: "Label - Copy",
		type: ControlType6.String,
	},
	bPCJyrIbK: {
		defaultValue:
			'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3 15L9.29412 20L21 4" stroke="black" stroke-width="2" stroke-linecap="square"/> </svg>',
		displayTextArea: false,
		title: "Icon - Copied",
		type: ControlType6.String,
	},
	rIGEnoYqD: {
		defaultValue: "Copied",
		displayTextArea: false,
		title: "Label - Copied",
		type: ControlType6.String,
	},
	b8ei7OpHv: {
		defaultValue:
			'var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255)) /* {"name":"12"} */',
		title: "BG",
		type: ControlType6.Color,
	},
	wr2g_fjxZ: {
		defaultValue: "rgb(212, 212, 212)",
		title: "BG - Hover",
		type: ControlType6.Color,
	},
	PbW7K4Unr: {
		defaultValue:
			'var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5)) /* {"name":"1"} */',
		title: "Icons",
		type: ControlType6.Color,
	},
	aCeOAHQBL: {
		defaultValue:
			"var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
		title: "Labels",
		type: ControlType6.Color,
	},
	qIDNNRI0q: {
		defaultValue: "Copied text.",
		displayTextArea: true,
		title: "Clipboard Content",
		type: ControlType6.String,
	},
});
addFonts(
	FramerTNRZ_28SA,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Medium.cyrillic-ext-M4WHNGTS.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Medium.cyrillic-JVU2PANX.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Medium.greek-ext-4KCQBEIZ.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Medium.greek-DPOQGN7L.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Medium.latin-ext-J4DBSW7F.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Medium.latin-Y3IVPL46.woff2",
					weight: "500",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Medium.vietnamese-PJV76O4P.woff2",
					weight: "500",
				},
			],
		},
		...SVGFonts,
		...ClipboardFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/imYcgvXCMaLH8sOQe2Jn/bDLOEC0dLq6c7IJidZgj/Apo5ZZ6Tz.js
var CopyButtonFonts = getFonts2(stdin_default2);
var enabledGestures2 = {
	Op_urnwX0: {
		hover: true,
	},
};
var cycleOrder2 = ["Op_urnwX0", "ss9qAgzMr"];
var serializationHash2 = "framer-Pof2D";
var variantClassNames2 = {
	Op_urnwX0: "framer-v-1xbncy3",
	ss9qAgzMr: "framer-v-1avo1d2",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0,
	delay: 0,
	duration: 0.3,
	type: "spring",
};
var transformTemplate12 = (_, t) => `translate(-50%, -50%) ${t}`;
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap2 = {
	Primary: "Op_urnwX0",
	Secondary: "ss9qAgzMr",
};
var Variants2 = motion3.create(React4.Fragment);
var getProps2 = ({ height, id, link, title, width, ...props }) => {
	return {
		...props,
		p4yJ9jM9K: title ?? props.p4yJ9jM9K ?? "COPY COMPONENT",
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "Op_urnwX0",
		WnHFwZXvc: link ?? props.WnHFwZXvc,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef4(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className,
		layoutId,
		variant,
		p4yJ9jM9K: p4yJ9jM9K2,
		WnHFwZXvc: WnHFwZXvc2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "Op_urnwX0",
		enabledGestures: enabledGestures2,
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<Link
						href={WnHFwZXvc2}
						motionChild={true}
						nodeId={"Op_urnwX0"}
						openInNewTab={false}
						scopeId={"Apo5ZZ6Tz"}
					>
						<motion3.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx2(scopingClassNames, "framer-1xbncy3", className, classNames)} framer-1c46gga`}
							data-framer-name={"Primary"}
							layoutDependency={layoutDependency}
							layoutId={"Op_urnwX0"}
							ref={refBinding}
							style={{
								backgroundColor: "rgb(0, 0, 0)",
								borderBottomLeftRadius: 12,
								borderBottomRightRadius: 12,
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
								boxShadow:
									"0px 0px 0px 3px rgb(255, 255, 255), 0px 0px 0px 2px rgb(0, 0, 0)",
								...style,
							}}
							variants={{
								"Op_urnwX0-hover": {
									boxShadow:
										"0px 0px 0px 3px rgb(255, 255, 255), 0px 0px 0px 5px rgb(0, 0, 0)",
								},
								ss9qAgzMr: {
									backgroundColor: "rgb(255, 255, 255)",
									boxShadow: "0px 0px 0px 2px rgb(217, 217, 217)",
								},
							}}
							{...addPropertyOverrides2(
								{
									"Op_urnwX0-hover": {
										"data-framer-name": void 0,
									},
									ss9qAgzMr: {
										"data-framer-name": "Secondary",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText2
								__fromCanvasComponent={true}
								className={"framer-1h7fuze"}
								fonts={["GF;Black Han Sans-regular"]}
								layoutDependency={layoutDependency}
								layoutId={"IjowqCfhG"}
								style={{
									"--extracted-r6o4lv": "rgb(255, 255, 255)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={p4yJ9jM9K2}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides2(
									{
										ss9qAgzMr: {
											children: (
												<React4.Fragment>
													<motion3.p
														dir={"auto"}
														style={{
															"--font-selector":
																"R0Y7QmxhY2sgSGFuIFNhbnMtcmVndWxhcg==",
															"--framer-font-family":
																'"Black Han Sans", "Black Han Sans Placeholder", sans-serif',
															"--framer-font-size": "15px",
															"--framer-line-height": "1em",
														}}
													>
														{"BOOKA CALL"}
													</motion3.p>
												</React4.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React4.Fragment>
									<motion3.p
										dir={"auto"}
										style={{
											"--font-selector": "R0Y7QmxhY2sgSGFuIFNhbnMtcmVndWxhcg==",
											"--framer-font-family":
												'"Black Han Sans", "Black Han Sans Placeholder", sans-serif',
											"--framer-font-size": "12px",
											"--framer-line-height": "1em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgb(255, 255, 255))",
										}}
									>
										<motion3.span
											style={{
												"--framer-font-size": "15px",
											}}
										>
											{"BOOK"}
										</motion3.span>
										<motion3.span
											style={{
												"--framer-font-size": "15px",
											}}
										>
											<motion3.br />
										</motion3.span>
										<motion3.span
											style={{
												"--framer-font-size": "13px",
											}}
										>
											{"A CALL"}
										</motion3.span>
									</motion3.p>
								</React4.Fragment>
							</RichText2>
							<ComponentViewportProvider2
								height={44}
								y={
									(componentViewport?.y || 0) +
									((componentViewport?.height || 40) * 0.5000000000000002 - 22)
								}
							>
								<SmartComponentScopedContainer
									className={"framer-154l6hg-container"}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"zJD9O8lOH-container"}
									nodeId={"zJD9O8lOH"}
									rendersWithMotion={true}
									scopeId={"Apo5ZZ6Tz"}
									style={{
										opacity: 0,
									}}
									transformTemplate={transformTemplate12}
								>
									{_jsx4(stdin_default2, {
										aCeOAHQBL:
											"var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
										b8ei7OpHv:
											"var(--token-20608b9f-0145-4a1e-b971-ee948ebbb015, rgb(255, 255, 255))",
										bcOKL_7fc:
											'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path fill-rule="evenodd" clip-rule="evenodd" d="M21 3H7V7H3V21H17V17H21V3ZM17 15H19V5H9V7H17V15Z" fill="white"/> </svg>',
										bPCJyrIbK:
											'<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"> <path d="M3 15L9.29412 20L21 4" stroke="black" stroke-width="2" stroke-linecap="square"/> </svg>',
										height: "100%",
										id: "zJD9O8lOH",
										layoutId: "zJD9O8lOH",
										PbW7K4Unr:
											"var(--token-419394a1-565d-4952-8ba3-b4f1eb92339c, rgb(5, 5, 5))",
										qIDNNRI0q:
											"https://framer.com/m/HoverMaskReveal-prod-GdFmJi.js",
										rIGEnoYqD: "Copied",
										style: {
											height: "100%",
										},
										variant: matchVariant("ZPBoeSRM1"),
										width: "100%",
										wr2g_fjxZ: "rgb(212, 212, 212)",
										zhU3xY_Ux: "Copy component",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider2>
						</motion3.a>
					</Link>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Pof2D.framer-1c46gga, .framer-Pof2D .framer-1c46gga { display: block; }",
	".framer-Pof2D.framer-1xbncy3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 40px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px 16px 0px 16px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-Pof2D .framer-1h7fuze { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-Pof2D .framer-154l6hg-container { flex: none; height: 44px; left: 50%; position: absolute; top: 50%; width: auto; z-index: 1; }",
];
var FramerApo5ZZ6Tz = withCSS2(Component2, css2, "framer-Pof2D");
var stdin_default3 = FramerApo5ZZ6Tz;
FramerApo5ZZ6Tz.displayName = "Button";
FramerApo5ZZ6Tz.defaultProps = {
	height: 40,
	width: 176.5,
};
addPropertyControls4(FramerApo5ZZ6Tz, {
	variant: {
		options: ["Op_urnwX0", "ss9qAgzMr"],
		optionTitles: ["Primary", "Secondary"],
		title: "Variant",
		type: ControlType7.Enum,
	},
	p4yJ9jM9K: {
		defaultValue: "COPY COMPONENT",
		displayTextArea: false,
		title: "Title",
		type: ControlType7.String,
	},
	onp4yJ9jM9KChange: {
		changes: "p4yJ9jM9K",
		type: ControlType7.ChangeHandler,
	},
	WnHFwZXvc: {
		title: "Link",
		type: ControlType7.Link,
	},
});
addFonts2(
	FramerApo5ZZ6Tz,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Black Han Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Black Han Sans",
					url: "https://fonts.gstatic.com/s/blackhansans/v24/ea8Aad44WunzF9a-dL6toA8r8nqQIXSkH-Hc.woff2",
					weight: "400",
				},
			],
		},
		...CopyButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerApo5ZZ6Tz.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default2, {}, context)]);
	},
};

// virtual:button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bd6f01237f00e787ad602818139e19184df527cab30eff70d27a6d1ac782b62c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bd6f01237f00e787ad602818139e19184df527cab30eff70d27a6d1ac782b62c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var button_default = ComponentWithRoot;
export { button_default as default };
