// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project bd6f01237f00e787 "Hover Mask Reveal - Community (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: '1' | '2' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-L62PYL7U.js";

// virtual:wireframe
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/468vnollhVaHn0aQx4VE/RIlijCcxEQTPZkVCSCYq/NyHQxQUOH.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["KmhZSyKuW", "rNhxVn09q"];
var serializationHash = "framer-h7qu0";
var variantClassNames = {
	KmhZSyKuW: "framer-v-fnhhlx",
	rNhxVn09q: "framer-v-12nxb24",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	duration: 0,
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 2,
	ease: [0.44, 0, 0.1, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	1: "KmhZSyKuW",
	2: "rNhxVn09q",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "KmhZSyKuW",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KmhZSyKuW",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear10fvnao = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("rNhxVn09q", true), 500);
	});
	const onAppear1q2opgh = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("KmhZSyKuW", true), 1500);
	});
	useOnVariantChange(baseVariant, {
		default: onAppear10fvnao,
		rNhxVn09q: onAppear1q2opgh,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							rNhxVn09q: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-fnhhlx",
							className,
							classNames,
						)}
						data-framer-name={"1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"KmhZSyKuW"}
						ref={refBinding}
						style={{
							mask: "linear-gradient(0deg, rgba(0, 0, 0, 0) 94%, rgb(0, 0, 0) 97%, rgba(0, 0, 0, 0) 100%) add",
							WebkitMask:
								"linear-gradient(0deg, rgba(0, 0, 0, 0) 94%, rgb(0, 0, 0) 97%, rgba(0, 0, 0, 0) 100%) add",
							...style,
						}}
						variants={{
							rNhxVn09q: {
								mask: "linear-gradient(0deg, rgba(0, 0, 0, 0) -24%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 24%) add",
								WebkitMask:
									"linear-gradient(0deg, rgba(0, 0, 0, 0) -24%, rgb(0, 0, 0) 0%, rgba(0, 0, 0, 0) 24%) add",
							},
						}}
						{...addPropertyOverrides(
							{
								rNhxVn09q: {
									"data-framer-name": "2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 1371,
								pixelWidth: 2400,
								sizes: componentViewport?.width || "100vw",
								src: "https://framerusercontent.com/images/jn3m32cwp8FMbhBSp3AxbdjaPE4.png?width=2400&height=1371",
								srcSet:
									"https://framerusercontent.com/images/jn3m32cwp8FMbhBSp3AxbdjaPE4.png?scale-down-to=512&width=2400&height=1371 512w,https://framerusercontent.com/images/jn3m32cwp8FMbhBSp3AxbdjaPE4.png?scale-down-to=1024&width=2400&height=1371 1024w,https://framerusercontent.com/images/jn3m32cwp8FMbhBSp3AxbdjaPE4.png?scale-down-to=2048&width=2400&height=1371 2048w,https://framerusercontent.com/images/jn3m32cwp8FMbhBSp3AxbdjaPE4.png?width=2400&height=1371 2400w",
							}}
							className={"framer-slk2cn"}
							data-framer-name={"Image"}
							draggable={"false"}
							layoutDependency={layoutDependency}
							layoutId={"LgDTyn2bT"}
							style={{
								opacity: 0.25,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-h7qu0.framer-xb53bq, .framer-h7qu0 .framer-xb53bq { display: block; }",
	".framer-h7qu0.framer-fnhhlx { height: 800px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 1200px; }",
	".framer-h7qu0 .framer-slk2cn { bottom: 0px; flex: none; left: 0px; overflow: var(--overflow-clip-fallback, clip); position: absolute; right: 0px; top: 0px; will-change: var(--framer-will-change-filter-override, filter); }",
];
var FramerNyHQxQUOH = withCSS(Component, css, "framer-h7qu0");
var stdin_default = FramerNyHQxQUOH;
FramerNyHQxQUOH.displayName = "Wireframe";
FramerNyHQxQUOH.defaultProps = {
	height: 800,
	width: 1200,
};
addPropertyControls(FramerNyHQxQUOH, {
	variant: {
		options: ["KmhZSyKuW", "rNhxVn09q"],
		optionTitles: ["1", "2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerNyHQxQUOH,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:wireframe
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KmhZSyKuW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bd6f01237f00e787ad602818139e19184df527cab30eff70d27a6d1ac782b62c"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WireframeFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"bd6f01237f00e787ad602818139e19184df527cab30eff70d27a6d1ac782b62c"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var wireframe_default = ComponentWithRoot;
export { wireframe_default as default };
